### ISSUE TITLE
_CastError (type 'Future<String?>' is not a subtype of type 'FutureOr<String>' in type cast)

### ISSUE THREAD

**Issue by i-amSid** [AgoraIO/Agora-Flutter-SDK#556]
Shows error when clicked 'Play Effect'
![Screenshot (20)](https://user-images.githubusercontent.com/95742800/148370556-89842a20-5bc0-4f48-b14d-3db7de87fa95.png)

**Comment by littleGnAl** [comment]
It's a known issue that had been fixed in our dev branch, we will merge it to the master branch later, to temporary fix it, you can try
https://github.com/AgoraIO/Agora-Flutter-SDK/blob/bd43d09b5ecab9da4f5043016734cca3ed9a99f5/example/lib/examples/basic/join_channel_audio/join_channel_audio.dart#L119
